[options]
girs_dir = "gir-files"
library = "Graphene"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Graphene.Euler",
    "Graphene.EulerOrder",
    "Graphene.Frustum",
    "Graphene.Matrix",
    "Graphene.Plane",
    "Graphene.Point",
    "Graphene.Point3D",
    "Graphene.Quad",
    "Graphene.Quaternion",
    "Graphene.Ray",
    "Graphene.Rect",
    "Graphene.Size",
    "Graphene.Triangle",
    "Graphene.Vec2",
    "Graphene.Vec3",
    "Graphene.Vec4",
]

[[object]]
name = "Graphene.*"
status = "generate"

[[object]]
name = "Graphene.Box"
status = "generate"
    [[object.function]]
    name = "init_from_points"
    #array with size
    ignore = true
    [[object.function]]
    name = "init_from_vectors"
    #array with size
    ignore = true

[[object]]
name = "Graphene.Sphere"
status = "generate"
    [[object.function]]
    name = "init_from_points"
    #array with size
    ignore = true
    [[object.function]]
    name = "init_from_vectors"
    #array with size
    ignore = true
