[options]
girs_dir = "gir-files"
library = "Graphene"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Graphene.Box",
    "Graphene.Euler",
    "Graphene.EulerOrder",
    "Graphene.Frustum",
    "Graphene.HAS_GCC",
    "Graphene.HAS_SCALAR",
    "Graphene.HAS_SSE",
    "Graphene.Matrix",
    "Graphene.PI",
    "Graphene.PI_2",
    "Graphene.Plane",
    "Graphene.Point",
    "Graphene.Point3D",
    "Graphene.Quad",
    "Graphene.Quaternion",
    "Graphene.Ray",
    "Graphene.Rect",
    "Graphene.SIMD_S",
    "Graphene.Simd4F",
    "Graphene.Simd4X4F",
    "Graphene.Size",
    "Graphene.Sphere",
    "Graphene.Triangle",
    "Graphene.VEC2_LEN",
    "Graphene.VEC3_LEN",
    "Graphene.VEC4_LEN",
    "Graphene.Vec2",
    "Graphene.Vec3",
    "Graphene.Vec4",
    "Graphene.box_empty",
    "Graphene.box_infinite",
    "Graphene.box_minus_one",
    "Graphene.box_one",
    "Graphene.box_one_minus_one",
    "Graphene.box_zero",
    "Graphene.false",
    "Graphene.point3d_zero",
    "Graphene.point_zero",
    "Graphene.rect_alloc",
    "Graphene.rect_zero",
    "Graphene.size_zero",
    "Graphene.true",
    "Graphene.vec2_one",
    "Graphene.vec2_x_axis",
    "Graphene.vec2_y_axis",
    "Graphene.vec2_zero",
    "Graphene.vec3_one",
    "Graphene.vec3_x_axis",
    "Graphene.vec3_y_axis",
    "Graphene.vec3_z_axis",
    "Graphene.vec3_zero",
    "Graphene.vec4_one",
    "Graphene.vec4_w_axis",
    "Graphene.vec4_x_axis",
    "Graphene.vec4_y_axis",
    "Graphene.vec4_z_axis",
    "Graphene.vec4_zero",
]
